### ISSUE TITLE
issue in __init__.py

### ISSUE THREAD

**Issue by Nefilime** [microsoft/python-sample-vscode-flask-tutorial#44]
Traceback (most recent call last):
  File "./hello_app/__init__.py", line 1, in <module>
    from flask import Flask  # Import the Flask class
ModuleNotFoundError: No module named 'flask'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. GAME OVER ***

**Comment by chinghwayu** [comment]
I know this is a year late but I just ran into this and resolved by changing the base image (which doesn't include flask) to:
```
tiangolo/uwsgi-nginx-flask:python3.8-alpine-2020-12-19
```
https://github.com/microsoft/python-sample-vscode-flask-tutorial/blob/c49c02d17ce0631f4fc1e1d87f4de69deca3ec26/Dockerfile#L2

**Comment by yorkzhang** [comment]
The issue seems happen again even "tiangolo/uwsgi-nginx-flask:python3.8-alpine-2020-12-19" is already changed to. It looks the new image from Dockerhub was not built properly so Flask is not installed in. 
An easy  way is just **uncommenting** below lines in Dockerfile:
#COPY requirements.txt /
#RUN pip install --no-cache-dir -U pip
#RUN pip install --no-cache-dir -r /requirements.txt

**Comment by elviromercic23-cmyk** [comment]
> I build image via dockerfile
> 
> When container start i see error in container.
> 
> Traceback (most recent call last):
>   File "./hello_app/__init__.py", line 1, in <module>
>     from flask import Flask  # Import the Flask class
> ModuleNotFoundError: No module named 'flask'
> unable to load app 0 (mountpoint='') (callable not found or import error)
> *** no app loaded. GAME OVER ***
> 
> 
>
